// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajavytutiilwgyjqrvja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqYXZ5dHV0aWlsd2d5anFydmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjUzODMsImV4cCI6MjA2NTU0MTM4M30.kMrvS8GSBZN1m_wLSHvdAQrazNIEQboKGNIMydQjzgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);